/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as MayoristaImport } from "./routes/mayorista"
import { Route as AboutImport } from "./routes/about"
import { Route as IndexImport } from "./routes/index"

// Create/Update Routes

const MayoristaRoute = MayoristaImport.update({
	path: "/mayorista",
	getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
	path: "/about",
	getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/"
			path: "/"
			fullPath: "/"
			preLoaderRoute: typeof IndexImport
			parentRoute: typeof rootRoute
		}
		"/about": {
			id: "/about"
			path: "/about"
			fullPath: "/about"
			preLoaderRoute: typeof AboutImport
			parentRoute: typeof rootRoute
		}
		"/mayorista": {
			id: "/mayorista"
			path: "/mayorista"
			fullPath: "/mayorista"
			preLoaderRoute: typeof MayoristaImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute
	"/about": typeof AboutRoute
	"/mayorista": typeof MayoristaRoute
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute
	"/about": typeof AboutRoute
	"/mayorista": typeof MayoristaRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	"/": typeof IndexRoute
	"/about": typeof AboutRoute
	"/mayorista": typeof MayoristaRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: "/" | "/about" | "/mayorista"
	fileRoutesByTo: FileRoutesByTo
	to: "/" | "/about" | "/mayorista"
	id: "__root__" | "/" | "/about" | "/mayorista"
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute
	AboutRoute: typeof AboutRoute
	MayoristaRoute: typeof MayoristaRoute
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AboutRoute: AboutRoute,
	MayoristaRoute: MayoristaRoute,
}

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/mayorista"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/mayorista": {
      "filePath": "mayorista.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
