name: Deploy to Railway

on:
  push:
    branches: 
      - dev

jobs:
  deploy:
    name: development CI
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "test"
      LOG_LEVEL: "debug"
      PORT: 4000
      NM_MAILTRAP_FROM: test@test.cl
      NM_MAILTRAP_RECEIVER_CONTACTO: test@test.cl
      NM_MAILTRAP_RECEIVER_VENTAS: test@test.cl 
      MT_API_KEY: ${{secrets.MT_API_KEY}}
      MT_ACCOUNT_ID: ${{ secrets.MT_ACCOUNT_ID }}
      MT_TEST_ID: ${{ secrets.MT_TEST_ID }}  
      VITE_MP_PUBLIC_KEY: test
      MP_ACCESS_TOKEN: ${{ secrets.MP_ACCESS_TOKEN }}
      MP_REDIRECT: https://test.cl
      MPW_SECRET: test
      VITE_STRAPI_API_KEY: test
      VITE_STRAPI_URL: https://test.cl
      SENTRY_DSN: https://test.io
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      DATABASE_URL: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Run Build
        run: bun run build

      - name: Run tests
        run: bun test
