name: Deploy to Railway

on:
  push:
    branches: [dev]

jobs:
  deploy:
    name: dev actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Run tests
        env:
          NODE_ENV: "test"
          LOG_LEVEL: "debug"
          PORT: 4000
          NM_MAILTRAP_FROM: test@test.cl
          NM_MAILTRAP_RECEIVER_CONTACTO: test@test.cl
          NM_MAILTRAP_RECEIVER_VENTAS: test@test.cl 
          MT_API_KEY: test
          MT_ACCOUNT_ID: 1
          MT_TEST_ID: 1
          VITE_MP_PUBLIC_KEY: test
          MP_ACCESS_TOKEN: test
          MP_REDIRECT: https://test.cl
          MPW_SECRET: test
          VITE_STRAPI_API_KEY: test
          VITE_STRAPI_URL: https://test.cl
          SENTRY_DSN: https://test.io
          WEBHOOK_URL: https://test.com
          DATABASE_URL: test
        run: bun test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
